spring:
 application:
   name: helloservice
server:
     port: 8094
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true #since the service needs to be fetched and registered
    service-url:
         defaultZone: http://localhost:8761/eureka # to know the location of where it runs
  instance: 
    hostname: localhost     


